title:        'Eugene Enlightened'
tagline:      'Willamette Valley Ingress Faction'
description:  'all your portals are belong to us. #toadsintrees'
url:          http://eugene-enlightened.github.io
version:      1.0
author:
  name:       ''
  email:      ''
permalink:    pretty
markdown: 	  rdiscount
